/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardExample: typeof import('./docs/components/CardExample.vue')['default']
    CodeEditor: typeof import('./docs/components/CodeEditor.vue')['default']
    CodeLayout: typeof import('./docs/components/CodeLayout.vue')['default']
    ColorHelper: typeof import('./docs/components/ColorHelper.vue')['default']
    ColorPalette: typeof import('./docs/components/ColorPalette.vue')['default']
    FooterNotes: typeof import('./docs/components/FooterNotes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableUtility: typeof import('./docs/components/TableUtility.vue')['default']
  }
}
