/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardExample: typeof import('./docs/components/CardExample.vue')['default']
    CodeEditor: typeof import('./docs/components/CodeEditor.vue')['default']
    CodeLayout: typeof import('./docs/components/CodeLayout.vue')['default']
    ColorHelper: typeof import('./docs/components/ColorHelper.vue')['default']
    ColorPalette: typeof import('./docs/components/ColorPalette.vue')['default']
    CopyCode: typeof import('./docs/components/CopyCode.vue')['default']
    FooterNotes: typeof import('./docs/components/FooterNotes.vue')['default']
    Logo: typeof import('./docs/components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableUtility: typeof import('./docs/components/TableUtility.vue')['default']
  }
}
