allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  vue-inbrowser-compiler-demi: true
minimumReleaseAgeExclude:
  - '@csstools/css-color-parser@4.1.7'
  - '@csstools/postcss-alpha-function@2.0.6'
  - '@csstools/postcss-color-function-display-p3-linear@2.0.5'
  - '@csstools/postcss-color-function@5.0.5'
  - '@csstools/postcss-color-mix-function@4.0.5'
  - '@csstools/postcss-color-mix-variadic-function-arguments@2.0.5'
  - '@csstools/postcss-contrast-color-function@3.0.5'
  - '@csstools/postcss-gamut-mapping@3.0.5'
  - '@csstools/postcss-gradients-interpolation-method@6.0.5'
  - '@csstools/postcss-hwb-function@5.0.5'
  - '@csstools/postcss-oklab-function@5.0.5'
  - '@csstools/postcss-relative-color-syntax@4.0.5'
  - postcss-color-functional-notation@8.0.5
  - postcss-lab-function@8.0.5
  - postcss-preset-env@11.3.1
